# CREATE IDP USER FOR KEYCLOAK WITH ADMIN ON SCHEMA
# REPLACE VARIABLES WITH ONE FROM GITLAB CI

set -e

psql -v ON_ERROR_STOP=1 --username "$ENV_PGSQL_ROOT_USER" --dbname "$ENV_PGSQL_ROOT_DB" <<-EOSQL
    CREATE USER $ENV_IDP_DEV_USER WITH PASSWORD '$ENV_IDP_DEV_PASSWORD';
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA $ENV_PGSQL_SCHEMA TO $ENV_IDP_DEV_USER;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA $ENV_PGSQL_SCHEMA TO $ENV_IDP_DEV_USER;
EOSQL