# CREATE READ ACCESS ROLE ON SCHEMA
# REPLACE VARIABLES WITH ONE FROM GITLAB CI

set -e

psql -v ON_ERROR_STOP=1 --username "$ENV_PGSQL_ROOT_USER" --dbname "$ENV_PGSQL_ROOT_DB" <<-EOSQL
    CREATE ROLE readaccess;
    GRANT CONNECT ON DATABASE $ENV_PGSQL_SCHEMA TO readaccess;
    GRANT USAGE ON SCHEMA $ENV_PGSQL_SCHEMA TO readaccess;
    GRANT SELECT ON ALL TABLES IN SCHEMA $ENV_PGSQL_SCHEMA TO readaccess;
    GRANT SELECT ON ALL SEQUENCES IN SCHEMA $ENV_PGSQL_SCHEMA TO readaccess;
    ALTER DEFAULT PRIVILEGES IN SCHEMA $ENV_PGSQL_SCHEMA GRANT SELECT ON TABLES TO readaccess;
EOSQL