# CREATE SERVICE USER WITH READ ACCESS RIGHT ON SCHEMA
# REPLACE VARIABLES WITH ONE FROM GITLAB CI

set -e

psql -v ON_ERROR_STOP=1 --username "$ENV_PGSQL_ROOT_USER" --dbname "$ENV_PGSQL_ROOT_DB" <<-EOSQL
    CREATE USER $ENV_PGSQL_SERVICE_USER WITH PASSWORD '$ENV_PGSQL_SERVICE_PASSWORD';
    GRANT readaccess TO $ENV_PGSQL_SERVICE_USER;
EOSQL