# INIT PGSQL BY ALTERING PUBLIC SCHEMA
# REPLACE VARIABLES WITH ONE FROM GITLAB CI

set -e

psql -v ON_ERROR_STOP=1 --username "$ENV_PGSQL_ROOT_USER" --dbname "$ENV_PGSQL_ROOT_DB" <<-EOSQL
    ALTER SCHEMA public RENAME TO $ENV_PGSQL_SCHEMA;
EOSQL