version: "3.8"

services:
  mariadb:
    image: ${MARIADB_IMAGE_NAME}
    command: --max_allowed_packet=67108864 # Set max_allowed_packet to 64MB (default value is 16MB and Matomo need of 64MB min for performed)
    environment:
      - MYSQL_USER=${MATOMO_DATABASE_USER_NAME}
      - MYSQL_PASSWORD=${MATOMO_DATABASE_USER_PWD}
      - MYSQL_DATABASE=${MATOMO_DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${MATOMO_DATABASE_ROOT_PWD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - dev_storage-nw
    deploy:
      labels:
        - "traefik.enable=false"

  matomo:
    image: ${MATOMO_IMAGE_NAME}
    environment:
      - MATOMO_USERNAME=${MATOMO_SUPER_USER}
      - MATOMO_PASSWORD=${MATOMO_SUPER_PASSWORD}
      - MATOMO_EMAIL=${MATOMO_SUPER_EMAIL}
      - MATOMO_DATABASE_HOST=${STACK_NAME}_mariadb
      - MATOMO_DATABASE_USER=${MATOMO_DATABASE_USER_NAME}
      - MATOMO_DATABASE_PASSWORD=${MATOMO_DATABASE_USER_PWD}
      - MATOMO_DATABASE_NAME=${MATOMO_DATABASE_NAME}
      - MATOMO_WEBSITE_NAME=${WEBSITE_FQDN}
      - MATOMO_WEBSITE_HOST=${WEBSITE_FQDN}
    volumes:
      - matomo_data:/bitnami/matomo
    depends_on:
      - mariadb
    networks:
      - dev_storage-nw
      - dev_web-nw
    ports:
      - "3306"
    deploy:
      labels:
        - "traefik.http.routers.${STACK_NAME}.entrypoints=http"
        - "traefik.http.routers.${STACK_NAME}.service=${STACK_NAME}"
        - "traefik.http.routers.${STACK_NAME}.rule=Host(`${MATOMO_FQDN}`)"
        - "traefik.http.routers.${STACK_NAME}.middlewares=${STACK_NAME}"
        - "traefik.http.middlewares.${STACK_NAME}.headers.customrequestheaders.X-Forwarded-Proto=https"
        - "traefik.http.services.${STACK_NAME}.loadbalancer.server.port=8080"
        - "traefik.http.services.${STACK_NAME}.loadbalancer.server.scheme=http"
        - "traefik.docker.network=dev_web-nw"
volumes:
  mariadb_data:
  matomo_data:

networks:
  dev_web-nw:
    external: true
    name: dev_web-nw
  dev_storage-nw:
    driver: overlay
    attachable: true
    internal: true
