version: '3'

services:
  admin:
    image: ${ADMIN_IMAGE_NAME}
    build:
      context: .
      dockerfile: ./admin-dockerfile.yml
      args:
        ADMIN_BASE_IMAGE_NAME: ${ADMIN_BASE_IMAGE_NAME}
    networks:
      - web-nw
    ports:
      - '8081'
    environment:
      - API_FQDN
      - IDP_FQDN
      - MCM_IDP_REALM
      - MCM_IDP_CLIENTID_ADMIN
    labels:
      - 'kompose.image-pull-secret=${GITLAB_IMAGE_PULL_SECRET_NAME}'
      - 'kompose.service.type=clusterip'
networks:
  web-nw:
