commonAnnotations:
  app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
  app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
  kubernetes.io/ingress.class: traefik

resources:
  - antivirus-ingressroute.yml
  # - antivirus-certificate.yml

patchesStrategicMerge:
  - web_nw_networkpolicy_namespaceselector.yml
