commonAnnotations:
  app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
  app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
  kubernetes.io/ingress.class: traefik

resources:
  - idp-ingressroute.yml
  - idp-headers-middleware.yml
  - idp-ratelimit-middleware.yml
  - idp-inflightreq-middleware.yml
  # - gk-ingressroute.yml
  # - gk-headers-middleware.yml
  # - gk-certificate.yml
  # - idp-certificate.yml

patchesStrategicMerge:
  - web_nw_networkpolicy_namespaceselector.yml
  - idp_deployment_set_fsgroup.yml
  - idp_deployment_set_realm_config.yml

configMapGenerator:
- name: mcm-realm-config
  files:
    - all-realm.json