commonAnnotations:
  app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
  app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
  kubernetes.io/ingress.class: traefik

resources:
  - admin-ingressroute.yml
  # - admin-certificate.yml

patchesStrategicMerge:
  - web_nw_networkpolicy_namespaceselector.yml
  - admin_configmap_volumes.yml

configMapGenerator:
  - name: admin-keycloak-config
    files:
      - keycloak.json
