/* 
 * CREATE ROOT USER
 * REPLACE VARIABLES WITH ONE FROM GITLAB CI
 * /!\ DB PASSWORD MUST NOT CONTAIN SPECIAL CHAR
 */

CREATE USER ${ENV_ANALYTICS_DB_DEV_USER} IDENTIFIED BY '${ENV_ANALYTICS_DB_DEV_PASSWORD}';
GRANT ALL PRIVILEGES ON ${ENV_ANALYTICS_DB_NAME}.* TO ${ENV_ANALYTICS_DB_DEV_USER};
FLUSH PRIVILEGES;