commonAnnotations:
  app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
  app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
  kubernetes.io/ingress.class: traefik

resources:
  - api-ingressroute.yml
  # - api-certificate.yml
  - api-headers-middleware.yml
  - api-ratelimit-middleware.yml
  - api-inflightreq-middleware.yml

patchesStrategicMerge:
  - web_nw_networkpolicy_namespaceselector.yml
